import {defineAsyncComponent} from 'vue'

import formBuilder from "./formBuilder";
import list from "./list";
import dialog from "./dialog";

import {Icon} from '@iconify/vue';

export const GlobalComponents = {
    Icon,
    Sortable: defineAsyncComponent(() => import('../components/basic/Sortable.vue')),
    VSimpleDatatables: defineAsyncComponent(() => import('../components/base/plugins/VSimpleDatatables.vue')),
    VLoader: defineAsyncComponent(() => import('../components/base/loader/VLoader.vue')),
    VFlexPagination: defineAsyncComponent(() => import('../components/base/pagination/VFlexPagination.vue')),
    VFilePond: defineAsyncComponent(() => import('../components/base/plugins/VFilePond.vue')),
    VButton: defineAsyncComponent(() => import('../components/base/button/VButton.vue')),
    Dashboard: defineAsyncComponent(() => import('../components/pages/dashboards/business/CompanyDashboard.vue')),
    VMessage: defineAsyncComponent(() => import('../components/base/message/VMessage.vue')),
    VIconWrap: defineAsyncComponent(() => import('../components/base/icon/VIconWrap.vue')),
    AnimatedLogo: defineAsyncComponent(() => import('../components/svg/AnimatedLogo.vue')),
    Toolbar: defineAsyncComponent(() => import('../components/partials/toolbars/Toolbar.vue')),
    ToolbarNotification: defineAsyncComponent(() => import('../components/partials/toolbars/ToolbarNotification.vue')),
    DashboardsSubsidebar: defineAsyncComponent(() => import('../layouts/sidebar-subsidebar/DashboardsSubsidebar.vue')),
    VTabs: defineAsyncComponent(() => import('../components/base/tabs/VTabs.vue')),
    VField: defineAsyncComponent(() => import('../components/base/form/VField.vue')),
    VSwitchBlock: defineAsyncComponent(() => import('../components/base/form/VSwitchBlock.vue')),
    VControl: defineAsyncComponent(() => import('../components/base/form/VControl.vue')),
    VAvatar: defineAsyncComponent(() => import('../components/base/avatar/VAvatar.vue')),
    DashboardsMobileSubsidebar: defineAsyncComponent(() => import('../layouts/mobile-subsidebars/DashboardsMobileSubsidebar.vue')),
    NotificationsMobileDropdown: defineAsyncComponent(() => import('../components/partials/dropdowns/NotificationsMobileDropdown.vue')),
    Sidebar: defineAsyncComponent(() => import('../components/navigation/desktop/Sidebar.vue')),
    UserProfileDropdown: defineAsyncComponent(() => import('../components/partials/dropdowns/UserProfileDropdown.vue')),
    MobileNavbar: defineAsyncComponent(() => import('../components/navigation/mobile/MobileNavbar.vue')),
    MobileSidebar: defineAsyncComponent(() => import('../components/navigation/mobile/MobileSidebar.vue')),
    VIcon: defineAsyncComponent(() => import('../components/base/icon/VIcon.vue')),
    VIconBox: defineAsyncComponent(() => import('../components/base/icon/VIconBox.vue')),
    VIconButton: defineAsyncComponent(() => import('../components/base/button/VIconButton.vue')),
    VDropdown: defineAsyncComponent(() => import('../components/base/dropdown/VDropdown.vue')),
    CircularMenu: defineAsyncComponent(() => import('../components/partials/circular-menu/CircularMenu.vue')),
    VBlock: defineAsyncComponent(() => import('../components/base/block/VBlock.vue')),
    UIWidget: defineAsyncComponent(() => import('../components/partials/widgets/ui-creative/UIWidget.vue')),
    CountriesPanel : defineAsyncComponent(() => import('../components/basic/panels/CountriesPanel.vue')),
    LanguagesPanel: defineAsyncComponent(() => import('../components/basic/panels/LanguagesPanel.vue')),
    VPlaceholderPage: defineAsyncComponent(() => import('../components/base/placeholder/VPlaceholderPage.vue')),
    VBreadcrumb: defineAsyncComponent(() => import('../components/base/breadcrumb/VBreadcrumb.vue')),
    ChatWindow: defineAsyncComponent(() => import('../components/chat/App.vue')),
    //     // VBreadcrumb:  import('../components/base/breadcrumb/VBreadcrumb.vue')['default'],
    ChatWindow: defineAsyncComponent(() => import('../components/chat/App.vue')),
//     // VPlaceholderPage:  import('../components/base/placeholder/VPlaceholderPage.vue')['default'],

    // ActivityPanel:  import('../components/partials/panels/ActivityPanel.vue')['default'],

    ...formBuilder,
    ...list,
    ...dialog,
};
//     // UIWidget:  import('../components/partials/widgets/ui-creative/UIWidget.vue')['default'],

// console.log('components',components);
// Object.entries(components).forEach((component) => {
//     GlobalComponents[component[0]] = defineAsyncComponent(() =>
//         import(`${component[1]}`)
//     );
// });

// export default GlobalComponents;


// "VMessage": VMessage,
// "VButton": VButton,
// "VIconWrap": VIconWrap,
// "LanguagesPanel": LanguagesPanel,
// "AnimatedLogo": AnimatedLogo,
// "Toolbar": Toolbar,
// "DashboardsSubsidebar": DashboardsSubsidebar,
// "NotificationsMobileDropdown": NotificationsMobileDropdown,
// "DashboardsMobileSubsidebar": DashboardsMobileSubsidebar,
// "Sidebar": Sidebar,
// "MobileNavbar": MobileNavbar,
// "MobileSidebar": MobileSidebar,
// "VAvatar": VAvatar,
// "UserProfileDropdown": UserProfileDropdown,
// "VIcon": VIcon,
// "VIconBox": VIconBox,
// "VIconButton": VIconButton,
// "VDropdown": VDropdown,
// "Dashboard": Dashboard,
// "VControl": VControl,
// "VSwitchBlock": VSwitchBlock,
// "VField": VField,
// "VTabs": VTabs,

// export const GlobalComponents = {
//     // ActionPageV1:  import('../components/pages/layouts/actions/ActionPageV1.vue')['default'],
//     // ActionPageV2:  import('../components/pages/layouts/actions/ActionPageV2.vue')['default'],
//     // ActivityPanel:  import('../components/partials/panels/ActivityPanel.vue')['default'],
//     // AnalyticsDashboard:  import('../components/pages/dashboards/finance/AnalyticsDashboard.vue')['default'],
//     // ApexDashboard:  import('../components/pages/charts/ApexDashboard.vue')['default'],
//     // AppLayout:  import('./src/layouts/AppLayout.vue')['default'],
//     // AuthLayout:  import('../layouts/AuthLayout.vue')['default'],
//     // AvatarListWidget:  import('../components/partials/widgets/ui-creative/AvatarListWidget.vue')['default'],
//     // BankingDashboardV1:  import('../components/pages/dashboards/banking/BankingDashboardV1.vue')['default'],
//     // BankingDashboardV2:  import('../components/pages/dashboards/banking/BankingDashboardV2.vue')['default'],
//     // BankingDashboardV3:  import('../components/pages/dashboards/banking/BankingDashboardV3.vue')['default'],
//     // BillboardJsDashboard:  import('../components/pages/charts/BillboardJsDashboard.vue')['default'],
//     // CallWidget:  import('../components/partials/widgets/ui-creative/CallWidget.vue')['default'],
//     // CardsGridV1:  import('../components/pages/layouts/cards-grid/CardsGridV1.vue')['default'],
//     // CardsGridV2:  import('../components/pages/layouts/cards-grid/CardsGridV2.vue')['default'],
//     // CardsGridV3:  import('../components/pages/layouts/cards-grid/CardsGridV3.vue')['default'],
//     // CardsGridV4:  import('../components/pages/layouts/cards-grid/CardsGridV4.vue')['default'],
//     // CartWidget:  import('../components/partials/widgets/ui-creative/CartWidget.vue')['default'],
//     // ChartDropdown:  import('../components/partials/dropdowns/ChartDropdown.vue')['default'],
//     // CircleChart:  import('../components/partials/widgets/misc/CircleChart.vue')['default'],
//     // CircularMenu:  import('../components/partials/circular-menu/CircularMenu.vue')['default'],
//     // CollapsedMessaging:  import('../components/partials/messaging/CollapsedMessaging.vue')['default'],
//     // ColorsDocumentation:  import('C:/laragon/www/vuero/documentation/elements/colors-documentation.md')['default'],
//     // CompanyDashboard:  import('../components/pages/dashboards/business/CompanyDashboard.vue')['default'],
//     // ComponentsMobileSubsidebar:  import('../layouts/mobile-subsidebars/ComponentsMobileSubsidebar.vue')['default'],
//     // ComponentsSubnav:  import('../layouts/navbar-items/ComponentsSubnav.vue')['default'],
//     // ComponentsSubsidebar:  import('../layouts/sidebar-subsidebar/ComponentsSubsidebar.vue')['default'],
//     // ConfirmAccount:  import('../components/pages/layouts/actions/ConfirmAccount.vue')['default'],
//     // ContactWidget:  import('../components/partials/widgets/ui-creative/ContactWidget.vue')['default'],
//     // ContentUnorderedListsDocumentation:  import('C:/laragon/www/vuero/documentation/elements/content/content-unordered-lists-documentation.md')['default'],
//     // CourseDashboard:  import('../components/pages/dashboards/business/CourseDashboard.vue')['default'],

//     // DatatableV1:  import('../components/pages/layouts/datatable/DatatableV1.vue')['default'],
//     // DatatableV2:  import('../components/pages/layouts/datatable/DatatableV2.vue')['default'],
//     // DatatableV3:  import('../components/pages/layouts/datatable/DatatableV3.vue')['default'],
//     // DatatableV4:  import('../components/pages/layouts/datatable/DatatableV4.vue')['default'],
//     // DatepickerBaseDocumentation:  import('C:/laragon/www/vuero/documentation/plugins/datepicker/datepicker-base-documentation.md')['default'],
//     // DatepickerRangeDocumentation:  import('C:/laragon/www/vuero/documentation/plugins/datepicker/datepicker-range-documentation.md')['default'],
//     // DatepickerTimeDocumentation:  import('C:/laragon/www/vuero/documentation/plugins/datepicker/datepicker-time-documentation.md')['default'],
//     // DatepickerTimeSingleDocumentation:  import('C:/laragon/www/vuero/documentation/plugins/datepicker/datepicker-time-single-documentation.md')['default'],
//     // DropdownButtonHoverDocumentation:  import('C:/laragon/www/vuero/documentation/dropdown/dropdown-button-hover-documentation.md')['default'],
//     // DropdownButtonSlotDocumentation:  import('C:/laragon/www/vuero/documentation/dropdown/dropdown-button-slot-documentation.md')['default'],
//     // DropdownColorsDocumentation:  import('C:/laragon/www/vuero/documentation/dropdown/dropdown-colors-documentation.md')['default'],
//     // DropdownDocumentation:  import('C:/laragon/www/vuero/documentation/dropdown/dropdown-documentation.md')['default'],
//     // DropdownExposeDocumentation:  import('C:/laragon/www/vuero/documentation/dropdown/dropdown-expose-documentation.md')['default'],
//     // DropdownModernDocumentation:  import('C:/laragon/www/vuero/documentation/dropdown/dropdown-modern-documentation.md')['default'],
//     // DropdownPropsDocumentation:  import('C:/laragon/www/vuero/documentation/dropdown/dropdown-props-documentation.md')['default'],
//     // DropdownSlotsDocumentation:  import('C:/laragon/www/vuero/documentation/dropdown/dropdown-slots-documentation.md')['default'],
//     // DropdownWithIconsDocumentation:  import('C:/laragon/www/vuero/documentation/dropdown/dropdown-with-icons-documentation.md')['default'],
//     // DropdownWithImagesDocumentation:  import('C:/laragon/www/vuero/documentation/dropdown/dropdown-with-images-documentation.md')['default'],
//     // EcommerceDashboardV1:  import('../components/pages/dashboards/business/EcommerceDashboardV1.vue')['default'],
//     // EditProfileExperience:  import('../components/pages/forms/edit-profile/EditProfileExperience.vue')['default'],
//     // EditProfileGeneral:  import('../components/pages/forms/edit-profile/EditProfileGeneral.vue')['default'],
//     // EditProfileSettings:  import('../components/pages/forms/edit-profile/EditProfileSettings.vue')['default'],
//     // EditProfileSkills:  import('../components/pages/forms/edit-profile/EditProfileSkills.vue')['default'],
//     // EditSettingItemDropdown:  import('../components/partials/dropdowns/EditSettingItemDropdown.vue')['default'],
//     // ElementsMobileSubsidebar:  import('../layouts/mobile-subsidebars/ElementsMobileSubsidebar.vue')['default'],
//     // ElementsSubnav:  import('../layouts/navbar-items/ElementsSubnav.vue')['default'],
//     // ElementsSubsidebar:  import('../layouts/sidebar-subsidebar/ElementsSubsidebar.vue')['default'],
//     // EmptySearch:  import('../components/pages/layouts/search/EmptySearch.vue')['default'],
//     // FacetSearch:  import('../components/pages/layouts/search/FacetSearch.vue')['default'],
//     // FileCardDropdown:  import('../components/partials/dropdowns/FileCardDropdown.vue')['default'],
//     // FileTileDropdown:  import('../components/partials/dropdowns/FileTileDropdown.vue')['default'],
//     // FlexListV1:  import('../components/pages/layouts/flex-list/FlexListV1.vue')['default'],
//     // FlexListV2:  import('../components/pages/layouts/flex-list/FlexListV2.vue')['default'],
//     // FlexListV3:  import('../components/pages/layouts/flex-list/FlexListV3.vue')['default'],
//     // FlexStatWidget:  import('../components/partials/widgets/stat/FlexStatWidget.vue')['default'],
//     // FlexTableDropdown:  import('../components/partials/dropdowns/FlexTableDropdown.vue')['default'],
//     // FlightResultsDropdown:  import('../components/partials/dropdowns/FlightResultsDropdown.vue')['default'],
//     // FlightsDashboard:  import('../components/pages/dashboards/business/FlightsDashboard.vue')['default'],
//     // FoodDeliveryApp:  import('../components/pages/apps/FoodDeliveryApp.vue')['default'],
//     // FormLayout:  import('../components/pages/forms/form-layout/FormLayout.vue')['default'],
//     // FormLayoutSeparate:  import('../components/pages/forms/form-layout/FormLayoutSeparate.vue')['default'],
//     // FormLayoutSplit:  import('../components/pages/forms/form-layout/FormLayoutSplit.vue')['default'],
//     // FormLayoutStacked:  import('../components/pages/forms/form-layout/FormLayoutStacked.vue')['default'],
//     // FormLayoutStepper:  import('../components/pages/forms/form-layout/FormLayoutStepper.vue')['default'],
//     // GraphDropdown:  import('../components/partials/dropdowns/GraphDropdown.vue')['default'],
//     // GroupedStatWidget:  import('../components/partials/widgets/stat/GroupedStatWidget.vue')['default'],
//     // HelpersDocumentation:  import('C:/laragon/www/vuero/documentation/elements/helpers-documentation.md')['default'],
//     // HubCard:  import('../components/partials/documentation/HubCard.vue')['default'],
//     // HumanRessourcesDashboard:  import('../components/pages/dashboards/business/HumanRessourcesDashboard.vue')['default'],
//     // IllustrationWidget:  import('../components/partials/widgets/ui-creative/IllustrationWidget.vue')['default'],
//     // InboxMessagesList:  import('../components/partials/inbox/messages/InboxMessagesList.vue')['default'],
//     // InfluencerDropdown:  import('../components/partials/dropdowns/InfluencerDropdown.vue')['default'],
//     // Invoice:  import('../components/pages/layouts/Invoice.vue')['default'],
//     // JobsDashboard:  import('../components/pages/dashboards/business/JobsDashboard.vue')['default'],
//     // KanbanApp:  import('../components/pages/apps/KanbanApp.vue')['default'],
//     // KanbanDropdown:  import('../components/partials/dropdowns/KanbanDropdown.vue')['default'],
//     // LandingComponents:  import('../components/partials/landing/LandingComponents.vue')['default'],
//     // LandingDemos:  import('../components/partials/landing/LandingDemos.vue')['default'],
//     // LandingEmptyNavigation:  import('../components/partials/landing/LandingEmptyNavigation.vue')['default'],
//     // LandingFooter:  import('../components/partials/landing/LandingFooter.vue')['default'],
//     // LandingLayout:  import('./src/layouts/LandingLayout.vue')['default'],
//     // LandingNavigation:  import('../components/partials/landing/LandingNavigation.vue')['default'],
//     // LanguagesPanel:  import('../components/partials/panels/LanguagesPanel.vue')['default'],
//     // LayoutsMobileSubsidebar:  import('../layouts/mobile-subsidebars/LayoutsMobileSubsidebar.vue')['default'],
//     // LayoutsSubnav:  import('../layouts/navbar-items/LayoutsSubnav.vue')['default'],
//     // LayoutsSubsidebar:  import('../layouts/sidebar-subsidebar/LayoutsSubsidebar.vue')['default'],
//     // LayoutSwitcher:  import('../layouts/layout-switcher/LayoutSwitcher.vue')['default'],
//     // LifestyleDashboardV1:  import('../components/pages/dashboards/lifestyle/LifestyleDashboardV1.vue')['default'],
//     // LifestyleDashboardV2:  import('../components/pages/dashboards/lifestyle/LifestyleDashboardV2.vue')['default'],
//     // LifestyleDashboardV3:  import('../components/pages/dashboards/lifestyle/LifestyleDashboardV3.vue')['default'],
//     // LifestyleDashboardV4:  import('../components/pages/dashboards/lifestyle/LifestyleDashboardV4.vue')['default'],
//     // LifestyleDashboardV5:  import('../components/pages/dashboards/lifestyle/LifestyleDashboardV5.vue')['default'],
//     // LineStatWidget:  import('../components/partials/widgets/stat/LineStatWidget.vue')['default'],
//     // ListViewV1Dropdown:  import('../components/partials/dropdowns/ListViewV1Dropdown.vue')['default'],
//     // ListWidgetFileDropdown:  import('../components/partials/dropdowns/ListWidgetFileDropdown.vue')['default'],
//     // ListWidgetFileList:  import('../components/partials/widgets/list/content/ListWidgetFileList.vue')['default'],
//     // ListWidgetIconTimeline:  import('../components/partials/widgets/list/content/ListWidgetIconTimeline.vue')['default'],
//     // ListWidgetMainDropdown:  import('../components/partials/dropdowns/ListWidgetMainDropdown.vue')['default'],
//     // ListWidgetSingle:  import('../components/partials/widgets/list/ListWidgetSingle.vue')['default'],
//     // ListWidgetTabbed:  import('../components/partials/widgets/list/ListWidgetTabbed.vue')['default'],
//     // ListWidgetTodoList:  import('../components/partials/widgets/list/content/ListWidgetTodoList.vue')['default'],
//     // ListWidgetTopicList:  import('../components/partials/widgets/list/content/ListWidgetTopicList.vue')['default'],
//     // ListWidgetUserList:  import('../components/partials/widgets/list/content/ListWidgetUserList.vue')['default'],
//     // MailboxPanel:  import('../components/partials/inbox/panel/MailboxPanel.vue')['default'],
//     // MapMarker:  import('../components/partials/maps/MapMarker.vue')['default'],
//     // MapsDashboard:  import('../components/pages/dashboards/business/MapsDashboard.vue')['default'],
//     // MarketingAbout:  import('../components/partials/marketing/MarketingAbout.vue')['default'],
//     // MarketingCTA:  import('../components/partials/marketing/MarketingCTA.vue')['default'],
//     // MarketingFeaturesIcons:  import('../components/partials/marketing/MarketingFeaturesIcons.vue')['default'],
//     // MarketingMockup:  import('../components/partials/marketing/MarketingMockup.vue')['default'],
//     // MarketingPricings:  import('../components/partials/marketing/MarketingPricings.vue')['default'],
//     // MarketingSideFeatures:  import('../components/partials/marketing/MarketingSideFeatures.vue')['default'],
//     // Message1:  import('../components/partials/inbox/message-details/Message1.vue')['default'],
//     // Message10:  import('../components/partials/inbox/message-details/Message10.vue')['default'],
//     // Message2:  import('../components/partials/inbox/message-details/Message2.vue')['default'],
//     // Message3:  import('../components/partials/inbox/message-details/Message3.vue')['default'],
//     // Message4:  import('../components/partials/inbox/message-details/Message4.vue')['default'],
//     // Message5:  import('../components/partials/inbox/message-details/Message5.vue')['default'],
//     // Message6:  import('../components/partials/inbox/message-details/Message6.vue')['default'],
//     // Message7:  import('../components/partials/inbox/message-details/Message7.vue')['default'],
//     // Message8:  import('../components/partials/inbox/message-details/Message8.vue')['default'],
//     // Message9:  import('../components/partials/inbox/message-details/Message9.vue')['default'],
//     // MessagesMobileSubsidebar:  import('../components/partials/messaging/MessagesMobileSubsidebar.vue')['default'],
//     // MessagesSubsidebar:  import('../components/partials/messaging/MessagesSubsidebar.vue')['default'],
//     // MessagingLayout:  import('../layouts/MessagingLayout.vue')['default'],
//     // MessagingToolbar:  import('../components/partials/toolbars/MessagingToolbar.vue')['default'],
//     // MinimalLayout:  import('../layouts/MinimalLayout.vue')['default'],
//     // Navbar:  import('../components/navigation/desktop/Navbar.vue')['default'],
//     // NavbarComponentsDropdown:  import('../layouts/navbar-dropdown-items/NavbarComponentsDropdown.vue')['default'],
//     // NavbarDashboardsDropdown:  import('../layouts/navbar-dropdown-items/NavbarDashboardsDropdown.vue')['default'],
//     // NavbarDropdownLayout:  import('../layouts/NavbarDropdownLayout.vue')['default'],
//     // NavbarElementsDropdown:  import('../layouts/navbar-dropdown-items/NavbarElementsDropdown.vue')['default'],
//     // NavbarLayout:  import('../layouts/NavbarLayout.vue')['default'],
//     // NavbarLayoutsDropdown:  import('../layouts/navbar-dropdown-items/NavbarLayoutsDropdown.vue')['default'],
//     // NavbarSearch:  import('../components/navigation/desktop/NavbarSearch.vue')['default'],
//     // NavbarSearchLayout:  import('../layouts/NavbarSearchLayout.vue')['default'],
//     // NotificationPage:  import('../components/pages/layouts/profile/NotificationPage.vue')['default'],
//     // OnboardingStandard:  import('../components/pages/layouts/onboarding/OnboardingStandard.vue')['default'],
//     // OnboardingV1:  import('../components/pages/layouts/onboarding/OnboardingV1.vue')['default'],
//     // OnboardingV2:  import('../components/pages/layouts/onboarding/OnboardingV2.vue')['default'],
//     // OnboardingV3:  import('../components/pages/layouts/onboarding/OnboardingV3.vue')['default'],
//     // OnboardingV4:  import('../components/pages/layouts/onboarding/OnboardingV4.vue')['default'],
//     // OnboardingV5:  import('../components/pages/layouts/onboarding/OnboardingV5.vue')['default'],
//     // PersonalDashboardV1:  import('../components/pages/dashboards/personal/PersonalDashboardV1.vue')['default'],
//     // PersonalDashboardV2:  import('../components/pages/dashboards/personal/PersonalDashboardV2.vue')['default'],
//     // PersonalDashboardV3:  import('../components/pages/dashboards/personal/PersonalDashboardV3.vue')['default'],
//     // PlaceloadV1:  import('../components/pages/layouts/placeload/PlaceloadV1.vue')['default'],
//     // PlaceloadV2:  import('../components/pages/layouts/placeload/PlaceloadV2.vue')['default'],
//     // PlaceloadV3:  import('../components/pages/layouts/placeload/PlaceloadV3.vue')['default'],
//     // PlaceloadV4:  import('../components/pages/layouts/placeload/PlaceloadV4.vue')['default'],
//     // ProjectCardDropdown:  import('../components/partials/dropdowns/ProjectCardDropdown.vue')['default'],
//     // ProjectDetailsV1:  import('../components/pages/layouts/projects/ProjectDetailsV1.vue')['default'],
//     // ProjectListDropdown:  import('../components/partials/dropdowns/ProjectListDropdown.vue')['default'],
//     // ProjectsQuickDropdown:  import('../components/partials/dropdowns/ProjectsQuickDropdown.vue')['default'],
//     // ProjectsToolbar:  import('../components/partials/toolbars/ProjectsToolbar.vue')['default'],
//     // ProjectsViewV1:  import('../components/pages/layouts/projects/ProjectsViewV1.vue')['default'],
//     // ProjectsViewV2:  import('../components/pages/layouts/projects/ProjectsViewV2.vue')['default'],
//     // ProjectsViewV3:  import('../components/pages/layouts/projects/ProjectsViewV3.vue')['default'],
//     // ProjectWidgetDropdown:  import('../components/partials/dropdowns/ProjectWidgetDropdown.vue')['default'],
//     // Promotion:  import('../components/pages/layouts/actions/Promotion.vue')['default'],
//     // SaasBillingApp:  import('../components/pages/apps/SaasBillingApp.vue')['default'],
//     // SalesDashboard:  import('../components/pages/dashboards/finance/SalesDashboard.vue')['default'],
//     // SearchPanel:  import('../components/partials/panels/SearchPanel.vue')['default'],
//     // SettingsProfile:  import('../components/pages/layouts/profile/SettingsProfile.vue')['default'],
//     // Sidebar:  import('../components/navigation/desktop/Sidebar.vue')['default'],
//     // SidebarLayout:  import('../layouts/SidebarLayout.vue')['default'],
//     // SoccerDashboard:  import('../components/pages/dashboards/business/SoccerDashboard.vue')['default'],
//     // SocialButtonsWidget:  import('../components/partials/widgets/ui-creative/SocialButtonsWidget.vue')['default'],
//     // SocialStatWidget:  import('../components/partials/widgets/stat/SocialStatWidget.vue')['default'],
//     // SparkStatWidget:  import('../components/partials/widgets/stat/SparkStatWidget.vue')['default'],
//     // StackPopoverContent:  import('../components/partials/popover/StackPopoverContent.vue')['default'],
//     // StockDashboard:  import('../components/pages/dashboards/finance/StockDashboard.vue')['default'],
//     // StockDropdown:  import('../components/partials/dropdowns/StockDropdown.vue')['default'],
//     // SVGErrorPlaceholder:  import('../components/svg/SVGErrorPlaceholder.vue')['default'],
//     // TabbedGridItem:  import('../components/partials/grids-users/TabbedGridItem.vue')['default'],
//     // TableWidget:  import('../components/partials/widgets/table/TableWidget.vue')['default'],
//     // TableWidgetRowMembers:  import('../components/partials/widgets/table/content/TableWidgetRowMembers.vue')['default'],
//     // TaskPanel:  import('../components/partials/panels/TaskPanel.vue')['default'],
//     // TeamCardDropdown:  import('../components/partials/dropdowns/TeamCardDropdown.vue')['default'],
//     // TilesGridV1:  import('../components/pages/layouts/tiles-grid/TilesGridV1.vue')['default'],
//     // TilesGridV2:  import('../components/pages/layouts/tiles-grid/TilesGridV2.vue')['default'],
//     // TilesGridV3:  import('../components/pages/layouts/tiles-grid/TilesGridV3.vue')['default'],
//     // ToolbarNotification:  import('../components/partials/toolbars/ToolbarNotification.vue')['default'],
//     // TooltipBaseDocumentation:  import('C:/laragon/www/vuero/documentation/tooltip/tooltip-base-documentation.md')['default'],
//     // TooltipColorsDocumentation:  import('C:/laragon/www/vuero/documentation/tooltip/tooltip-colors-documentation.md')['default'],
//     // TooltipShapesDocumentation:  import('C:/laragon/www/vuero/documentation/tooltip/tooltip-shapes-documentation.md')['default'],
//     // UIWidgetCreativeList:  import('../components/partials/widgets/ui-creative/content/UIWidgetCreativeList.vue')['default'],
//     // UIWidgetDays:  import('../components/partials/widgets/ui-creative/content/UIWidgetDays.vue')['default'],
//     // UIWidgetFollowerStats:  import('../components/partials/widgets/ui-creative/content/UIWidgetFollowerStats.vue')['default'],
//     // UIWidgetIconList:  import('../components/partials/widgets/ui-creative/content/UIWidgetIconList.vue')['default'],
//     // UIWidgetInboxMessage:  import('../components/partials/widgets/ui-creative/content/UIWidgetInboxMessage.vue')['default'],
//     // UIWidgetMovie:  import('../components/partials/widgets/ui-creative/content/UIWidgetMovie.vue')['default'],
//     // UIWidgetNotifications:  import('../components/partials/widgets/ui-creative/content/UIWidgetNotifications.vue')['default'],
//     // UIWidgetTagList:  import('../components/partials/widgets/ui-creative/content/UIWidgetTagList.vue')['default'],
//     // UIWidgetToolbarDropdown:  import('../components/partials/widgets/ui-creative/toolbar/UIWidgetToolbarDropdown.vue')['default'],
//     // UIWidgetToolbarFollowers:  import('../components/partials/widgets/ui-creative/toolbar/UIWidgetToolbarFollowers.vue')['default'],
//     // UIWidgetToolbarIcon:  import('../components/partials/widgets/ui-creative/toolbar/UIWidgetToolbarIcon.vue')['default'],
//     // UIWidgetToolbarIcons:  import('../components/partials/widgets/ui-creative/toolbar/UIWidgetToolbarIcons.vue')['default'],
//     // UserCardDropdown:  import('../components/partials/dropdowns/UserCardDropdown.vue')['default'],
//     // UserPopoverContent:  import('../components/partials/popover/UserPopoverContent.vue')['default'],
//     // UsersGridV1:  import('../components/pages/layouts/users-grid/UsersGridV1.vue')['default'],
//     // UsersGridV2:  import('../components/pages/layouts/users-grid/UsersGridV2.vue')['default'],
//     // UsersGridV3:  import('../components/pages/layouts/users-grid/UsersGridV3.vue')['default'],
//     // UsersGridV4:  import('../components/pages/layouts/users-grid/UsersGridV4.vue')['default'],
//     // VAccordion:  import('../components/base/accordion/VAccordion.vue')['default'],
//     // VAccordionImage:  import('../components/base/accordion/VAccordionImage.vue')['default'],
//     // VAction:  import('../components/base/button/VAction.vue')['default'],
//     // VAnimatedCheckbox:  import('../components/base/form/VAnimatedCheckbox.vue')['default'],
//     // VAvatarStack:  import('../components/base/avatar/VAvatarStack.vue')['default'],
//     // VBillboardJS:  import('../components/base/plugins/VBillboardJS.vue')['default'],
//     // VButton: import('../components/base/button/VButton.vue'),
//     // VButtons:  import('../components/base/button/VButtons.vue')['default'],
//     // VCard:  import('../components/base/card/VCard.vue')['default'],
//     // VCardAction:  import('../components/base/card/VCardAction.vue')['default'],
//     // VCardAdvanced:  import('../components/base/card/VCardAdvanced.vue')['default'],
//     // VCardMedia:  import('../components/base/card/VCardMedia.vue')['default'],
//     // VCardSocial:  import('../components/base/card/VCardSocial.vue')['default'],
//     // VCheckbox:  import('../components/base/form/VCheckbox.vue')['default'],
//     // VCollapse:  import('../components/base/accordion/VCollapse.vue')['default'],
//     // VCollapseModel:  import('../components/base/accordion/VCollapseModel.vue')['default'],
//     // VCreditCard:  import('../components/base/plugins/VCreditCard.vue')['default'],
//     // VFlex:  import('../components/base/flex/VFlex.vue')['default'],
//     // VFlexItem:  import('../components/base/flex/VFlexItem.vue')['default'],
//     // VFlexPagination:  import('../components/base/pagination/VFlexPagination.vue')['default'],
//     // VFlexTable:  import('../components/base/table/VFlexTable.vue')['default'],
//     // VFlexTableRowBase:  import('../components/base/table/VFlexTableRowBase.vue')['default'],
//     // VFlexTableRowMedia:  import('../components/base/table/VFlexTableRowMedia.vue')['default'],
//     // VFlexTableRowOrders:  import('../components/base/table/VFlexTableRowOrders.vue')['default'],
//     // VGrid:  import('../components/base/grid/VGrid.vue')['default'],
//     // VGridItem:  import('../components/base/grid/VGridItem.vue')['default'],

//     // ViewListV1:  import('../components/pages/layouts/view-list/ViewListV1.vue')['default'],
//     // ViewListV2:  import('../components/pages/layouts/view-list/ViewListV2.vue')['default'],
//     // ViewListV3:  import('../components/pages/layouts/view-list/ViewListV3.vue')['default'],
//     // ViewListV4:  import('../components/pages/layouts/view-list/ViewListV4.vue')['default'],
//     // ViewProfile:  import('../components/pages/layouts/profile/ViewProfile.vue')['default'],
//     // VIMaskInput:  import('../components/base/plugins/VIMaskInput.vue')['default'],
//     // VLoader:  import('../components/base/loader/VLoader.vue')['default'],
//     // VModal:  import('../components/base/modal/VModal.vue')['default'],
//     // VPeity:  import('../components/base/plugins/VPeity.vue')['default'],
//     // VPhotosSwipe:  import('../components/base/plugins/VPhotosSwipe.vue')['default'],
//     // VPlaceholderPageDocumentation:  import('C:/laragon/www/vuero/documentation/placeholder-page/v-placeholder-page-documentation.md')['default'],
//     // VPlaceholderPagePropsDocumentation:  import('C:/laragon/www/vuero/documentation/placeholder-page/v-placeholder-page-props-documentation.md')['default'],
//     // VPlaceholderPageSlotsDocumentation:  import('C:/laragon/www/vuero/documentation/placeholder-page/v-placeholder-page-slots-documentation.md')['default'],
//     // VPlaceholderSection:  import('../components/base/placeholder/VPlaceholderSection.vue')['default'],
//     // VPlaceholderSectionDocumentation:  import('C:/laragon/www/vuero/documentation/placeholder-section/v-placeholder-section-documentation.md')['default'],
//     // VPlaceholderSectionPropsDocumentation:  import('C:/laragon/www/vuero/documentation/placeholder-section/v-placeholder-section-props-documentation.md')['default'],
//     // VPlaceholderSectionSlotsDocumentation:  import('C:/laragon/www/vuero/documentation/placeholder-section/v-placeholder-section-slots-documentation.md')['default'],
//     // VPlaceload:  import('../components/base/loader/VPlaceload.vue')['default'],
//     // VPlaceloadAvatar:  import('../components/base/loader/VPlaceloadAvatar.vue')['default'],
//     // VPlaceloadText:  import('../components/base/loader/VPlaceloadText.vue')['default'],
//     // VPlaceloadWrap:  import('../components/base/loader/VPlaceloadWrap.vue')['default'],
//     // VPlyr:  import('../components/base/plugins/VPlyr.vue')['default'],
//     // VProgress:  import('../components/base/progress/VProgress.vue')['default'],
//     // VProgressBaseDocumentation:  import('C:/laragon/www/vuero/documentation/progress/v-progress-base-documentation.md')['default'],
//     // VProgressColorsDocumentation:  import('C:/laragon/www/vuero/documentation/progress/v-progress-colors-documentation.md')['default'],
//     // VProgressPropsDocumentation:  import('C:/laragon/www/vuero/documentation/progress/v-progress-props-documentation.md')['default'],
//     // VProgressUndeterminateDocumentation:  import('C:/laragon/www/vuero/documentation/progress/v-progress-undeterminate-documentation.md')['default'],
//     // VRadio:  import('../components/base/form/VRadio.vue')['default'],
//     // VReloadPrompt:  import('../components/base/modal/VReloadPrompt.vue')['default'],
//     // VSnack:  import('../components/base/snack/V-Snack.vue')['default'],
//     // VSnackBaseDocumentation:  import('C:/laragon/www/vuero/documentation/snack/v-snack-base-documentation.md')['default'],
//     // VSnackFaDocumentation:  import('C:/laragon/www/vuero/documentation/snack/v-snack-fa-documentation.md')['default'],
//     // VSnackFaSolidDocumentation:  import('C:/laragon/www/vuero/documentation/snack/v-snack-fa-solid-documentation.md')['default'],
//     // VSnackFeatherDocumentation:  import('C:/laragon/www/vuero/documentation/snack/v-snack-feather-documentation.md')['default'],
//     // VSnackFeatherSolidDocumentation:  import('C:/laragon/www/vuero/documentation/snack/v-snack-feather-solid-documentation.md')['default'],
//     // VSnackLineDocumentation:  import('C:/laragon/www/vuero/documentation/snack/v-snack-line-documentation.md')['default'],
//     // VSnackLineSolidDocumentation:  import('C:/laragon/www/vuero/documentation/snack/v-snack-line-solid-documentation.md')['default'],
//     // VSnackPropsDocumentation:  import('C:/laragon/www/vuero/documentation/snack/v-snack-props-documentation.md')['default'],
//     // VSnackSmallIconDocumentation:  import('C:/laragon/www/vuero/documentation/snack/v-snack-small-icon-documentation.md')['default'],
//     // VSnackSmallImageDocumentation:  import('C:/laragon/www/vuero/documentation/snack/v-snack-small-image-documentation.md')['default'],
//     // VSnackWhiteDocumentation:  import('C:/laragon/www/vuero/documentation/snack/v-snack-white-documentation.md')['default'],
//     // VSwitchSegment:  import('../components/base/form/VSwitchSegment.vue')['default'],
//     // VTabs:  import('../components/base/tabs/VTabs.vue')['default'],
//     // VTag:  import('../components/base/tags/VTag.vue')['default'],
//     // VTagAddonsDocumentation:  import('C:/laragon/www/vuero/documentation/tag/v-tag-addons-documentation.md')['default'],
//     // VTagBaseDocumentation:  import('C:/laragon/www/vuero/documentation/tag/v-tag-base-documentation.md')['default'],
//     // VTagCurvedDocumentation:  import('C:/laragon/www/vuero/documentation/tag/v-tag-curved-documentation.md')['default'],
//     // VTagElevatedDocumentation:  import('C:/laragon/www/vuero/documentation/tag/v-tag-elevated-documentation.md')['default'],
//     // VTagLightDocumentation:  import('C:/laragon/www/vuero/documentation/tag/v-tag-light-documentation.md')['default'],
//     // VTagListDocumentation:  import('C:/laragon/www/vuero/documentation/tag/v-tag-list-documentation.md')['default'],
//     // VTagOutlinedDocumentation:  import('C:/laragon/www/vuero/documentation/tag/v-tag-outlined-documentation.md')['default'],
//     // VTagPropsDocumentation:  import('C:/laragon/www/vuero/documentation/tag/v-tag-props-documentation.md')['default'],
//     // VTagRoundedDocumentation:  import('C:/laragon/www/vuero/documentation/tag/v-tag-rounded-documentation.md')['default'],
//     // VTags:  import('../components/base/tags/VTags.vue')['default'],
//     // VTagsPropsDocumentation:  import('C:/laragon/www/vuero/documentation/tag/v-tags-props-documentation.md')['default'],
//     // VVivus:  import('../components/base/plugins/VVivus.vue')['default'],
//     // WebappConversation1:  import('../components/partials/messaging/WebappConversation1.vue')['default'],
//     // WebappConversation10:  import('../components/partials/messaging/WebappConversation10.vue')['default'],
//     // WebappConversation11:  import('../components/partials/messaging/WebappConversation11.vue')['default'],
//     // WebappConversation2:  import('../components/partials/messaging/WebappConversation2.vue')['default'],
//     // WebappConversation3:  import('../components/partials/messaging/WebappConversation3.vue')['default'],
//     // WebappConversation4:  import('../components/partials/messaging/WebappConversation4.vue')['default'],
//     // WebappConversation5:  import('../components/partials/messaging/WebappConversation5.vue')['default'],
//     // WebappConversation6:  import('../components/partials/messaging/WebappConversation6.vue')['default'],
//     // WebappConversation7:  import('../components/partials/messaging/WebappConversation7.vue')['default'],
//     // WebappConversation8:  import('../components/partials/messaging/WebappConversation8.vue')['default'],
//     // WebappConversation9:  import('../components/partials/messaging/WebappConversation9.vue')['default'],
//     // WebappConversationList:  import('../components/partials/messaging/WebappConversationList.vue')['default'],
//     // WidgetDropdown:  import('../components/partials/dropdowns/WidgetDropdown.vue')['default'],
//     // WidgetsCreative:  import('../components/pages/layouts/widgets/WidgetsCreative.vue')['default'],
//     // WidgetsList:  import('../components/pages/layouts/widgets/WidgetsList.vue')['default'],
//     // WidgetsStats:  import('../components/pages/layouts/widgets/WidgetsStats.vue')['default'],
//     // WidgetsUI:  import('../components/pages/layouts/widgets/WidgetsUI.vue')['default'],
//     // WizardV1Navigation:  import('../components/partials/wizard/WizardV1Navigation.vue')['default'],
//     // WizardV1Step1:  import('../components/partials/wizard/WizardV1Step1.vue')['default'],
//     // WizardV1Step2:  import('../components/partials/wizard/WizardV1Step2.vue')['default'],
//     // WizardV1Step3:  import('../components/partials/wizard/WizardV1Step3.vue')['default'],
//     // WizardV1Step4:  import('../components/partials/wizard/WizardV1Step4.vue')['default'],
//     // WizardV1Step5:  import('../components/partials/wizard/WizardV1Step5.vue')['default'],
//     // WizardV1Step6:  import('../components/partials/wizard/WizardV1Step6.vue')['default'],
//     // WizardV1Step7:  import('../components/partials/wizard/WizardV1Step7.vue')['default'],
//     // WizardV1Step8:  import('../components/partials/wizard/WizardV1Step8.vue')['default'],
// };
